version: '3.3'

services:

  atcsvc:
    image: atc/atcsvc:${TAG:-latest}
    build:
      context: .
      dockerfile: atcsvc/Dockerfile  
    depends_on:
      - airplanesvc
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://localhost:5023/
      - AIRPLANESVC_SERVICE_HOST=localhost
      - AIRPLANESVC_SERVICE_PORT=5024
    ports:
      - 5023:5023

  airplanesvc:
    image: atc/airplanesvc:${TAG:-latest}
    build:
      context: .
      dockerfile: airplanesvc/Dockerfile  
    environment:
      - ASPNETCORE_URLS=http://localhost:5024/
    ports:
      - 5024:5024
