{{- $service_name := "airplanesvc" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: {{ $service_name }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5024
  selector:
    app: atcApp
    component: {{ $service_name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: {{ $service_name }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/airplanesvc:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5024
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5024/
          livenessProbe:
            httpGet:
              path: /api/airplane/health
              port: 5024
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
        - name: fluentdsidecar
          image: {{ .Values.container_registry }}/fluentdsidecar:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          env:
            - name: INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: appinsights_instrumentationkey
{{ include "atcApp.k8s.envvars" (dict "service_name" $service_name) | indent 12 }}
        - name: telegrafsidecar
          image: {{ .Values.container_registry }}/telegraf:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: appinsights_instrumentationkey
{{ include "atcApp.k8s.envvars" (dict "service_name" $service_name) | indent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: config-files
          items:
          - key: telegraf.conf
            path: telegraf.conf