{{- $service_name := "airplanesvc" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: {{ $service_name }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5024
  selector:
    app: atcApp
    component: {{ $service_name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: {{ $service_name }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/airplanesvc:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5024
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5024/
            - name: METRICS_PORT
              value: 8186
          livenessProbe:
            httpGet:
              path: /api/airplane/health
              port: 5024
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
{{ include "atcApp.fluentdSidecar" (dict "service_name" $service_name "Values" .Values) | indent 8 }}
{{ include "atcApp.telegrafSidecar" (dict "service_name" $service_name "Values" .Values) | indent 8 }}
      volumes:
{{ include "atcApp.telegrafConfigVolume" . | indent 6 }}
