apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: airplanesvc
  name: airplanesvc
spec:
  ports:
    - port: 5024
  selector:
    app: atcApp
    component: airplanesvc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airplanesvc
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: airplanesvc
    spec:
      containers:
        - name: airplanesvc
          image: {{ .Values.container_registry }}/airplanesvc:{{ .Values.image_tag | trim }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5024
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5024/
          livenessProbe:
            httpGet:
              path: /api/airplane/health
              port: 5024
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
        - name: fluentdsidecar
          image: {{ .Values.container_registry }}/fluentdsidecar:{{ .Values.image_tag | trim }}
          env:
            - name: INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: appinsights_instrumentationkey
            - name: SOURCE_CONTAINER_NAME
              value: airplanesvc
