{{- $service_name := "airplanesvc" }}
{{- $context := (dict "service_name" $service_name "Values" .Values "Release" .Release) }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "atcApp.std.labels" $context | indent 4 }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5024
  selector:
{{ include "atcApp.std.labels" $context | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  selector:
    matchLabels:
{{ include "atcApp.std.labels" $context | indent 6 }}
  template:
    metadata:
      labels:
{{ include "atcApp.std.labels" $context | indent 8 }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/airplanesvc:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5024
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5024/
            - name: METRICS_PORT
              value: "8186"
          livenessProbe:
            httpGet:
              path: /api/airplane/health
              port: 5024
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
{{ include "atcApp.fluentdSidecar" $context| indent 8 }}
{{ include "atcApp.telegrafSidecar" $context | indent 8 }}
      volumes:
{{ include "atcApp.telegrafConfigVolume" . | indent 6 }}
{{ include "atcApp.fluentdConsoleLogVolume" . | indent 6 }}
