apiVersion: v1
kind: Secret
metadata:
  name: atc-secrets
type: Opaque
data:
  appinsights_instrumentationkey: {{ .Values.appinsights_instrumentationkey | b64enc }}
  azure_storage_connection_string: {{ .Values.appinsights_instrumentationkey | b64enc }}