apiVersion: v1
kind: Secret
metadata:
  name: atc-secrets
  app: atcApp
  release: {{ .Release.Name }}
type: Opaque
data:
  appinsights_instrumentationkey: {{ .Values.appinsights_instrumentationkey | b64enc }}
  azure_storage_connection_string: {{ .Values.azure_storage_connection_string | b64enc }}