{{- $service_name := "atcsvc" }}
{{- $service_port := 5023 }}
{{- $context := (dict "service_name" $service_name "service_port" $service_port "Values" .Values "Release" .Release) }}

apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "atcApp.std.labels" $context | indent 4 }}
  name: {{ $service_name }}
spec:
  ports:
    - port: {{ $service_port }}
  selector:
{{ include "atcApp.std.labels" $context | indent 4 }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service_name }}
  labels:
{{ include "atcApp.std.labels" $context | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "atcApp.std.labels" $context | indent 6 }}
  template:
    metadata:
      labels:
{{ include "atcApp.std.labels" $context | indent 8 }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/atcsvc:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $service_port }}
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:{{ $service_port }}/
            - name: METRICS_MODE
              value: {{ .Values.metrics_mode }}
            {{- if eq .Values.metrics_mode "push" }}
            - name: METRICS_PORT
              value: "8186"
            {{- end }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: azure_storage_connection_string
          livenessProbe:
            httpGet:
              path: /api/flights/health
              port: {{ $service_port }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
{{ include "atcApp.fluentdSidecar" $context | indent 8 }}
{{ include "atcApp.telegrafSidecar" $context | indent 8 }}
      volumes:
{{ include "atcApp.telegrafConfigVolume" . | indent 6 }}
{{ include "atcApp.fluentdConsoleLogVolume" . | indent 6 }}

