{{- $service_name := "frontend" }}
{{- $context := (dict "service_name" $service_name "Values" .Values "Release" .Release) }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "atcApp.std.labels" $context | indent 4 }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5022
      targetPort: 5000
  selector:
{{ include "atcApp.std.labels" $context | indent 4 }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  selector:
    matchLabels:
{{ include "atcApp.std.labels" $context | indent 6 }}
  template:
    metadata:
      labels:
{{ include "atcApp.std.labels" $context | indent 8 }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/frontend:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
{{ include "atcApp.fluentdSidecar" $context | indent 8 }}
      volumes:
{{ include "atcApp.fluentdConsoleLogVolume" . | indent 6 }}
