{{- $service_name := "frontend" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: {{ $service_name }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5022
      targetPort: 5000
  selector:
    app: atcApp
    component: {{ $service_name }}
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: {{ $service_name }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/frontend:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
{{ include "atcApp.fluentdSidecar" (dict "service_name" $service_name "Values" .Values) | indent 8 }}
