apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: frontend
  name: frontend
spec:
  ports:
    - port: 5022
      targetPort: 5000
  selector:
    app: atcApp
    component: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.container_registry }}/frontend:{{ .Values.image_tag | trim }}
          ports:
            - containerPort: 80
        - name: fluentdsidecar
          image: {{ .Values.container_registry }}/fluentdsidecar:{{ .Values.image_tag | trim }}
          env:
            - name: INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: appinsights_instrumentationkey
            - name: SOURCE_CONTAINER_NAME
              value: frontend

