{{- $service_name := "frontend" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atcApp
    component: {{ $service_name }}
  name: {{ $service_name }}
spec:
  ports:
    - port: 5022
      targetPort: 5000
  selector:
    app: atcApp
    component: {{ $service_name }}
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $service_name }}
spec:
  template:
    metadata:
      labels:
        app: atcApp
        component: {{ $service_name }}
    spec:
      containers:
        - name: {{ $service_name }}
          image: {{ .Values.container_registry }}/frontend:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: fluentdsidecar
          image: {{ .Values.container_registry }}/fluentdsidecar:{{ .Values.image_tag | trim }}
          imagePullPolicy: Always
          env:
            - name: INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: appinsights_instrumentationkey
{{ include "atcApp.k8s.envvars" (dict "service_name" $service_name) | indent 12 }}

