apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: telegraf
  name: telegraf
spec:
  ports:
  - port: 8186
    name: "http-listener"
  selector:
    app: eshop
    component: telegraf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telegraf
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: telegraf
    spec:
      containers:
      - name: telegraf
        image: kzeshopjan2018.azurecr.io/telegraf-ai:201802161631
        imagePullPolicy: Always
        ports:
        - containerPort: 8186
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom: 
            secretKeyRef:
              name: eshop-secrets
              key: appinsights_instrumentationkey
      volumes:
      - name: config
        configMap:
          name: config-files
          items:
          - key: telegraf.conf
            path: telegraf.conf