# Default values for eShop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Example:
# imageTag: "latest"

appinsights_instrumentationkey: ""
azure_storage_connection_string: ""
container_registry: ""
image_tag: "latest"
